lsi: false
highlighter: pygments
permalink: /:title/
relative_permalinks: false
sass:
  sass_dir: _sass
  style: :expanded

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems:
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.markdown
  - Gemfile
  - Gemfile.lock
  - Procfile

