lsi: false
paginate: 5
permalink: /:year/:month/:title/
markdown: rdiscount
pygments: true
title: subosito
url: http://subosito.com/
feed: http://feeds.feedburner.com/subosito
email: subosito@gmail.com
author: Alif Rachmawadi
username: subosito
accounts:
  twitter: https://twitter.com/#!/subosito
  github: https://github.com/subosito
  pinboard: https://pinboard.in/u:subosito/
  delicious: http://delicious.com/subosito
  stackoverflow: http://stackoverflow.com/users/94947/subosito
  google: https://plus.google.com/107350708236214972935
  facebook: https://www.facebook.com/subosito
  openid: https://subosito.myopenid.com
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
